### PR TITLE
related to #34 & #30 with refinements and bugfixes & impl #25

### PR DESCRIPTION
**Pull request by hosseinamin**
1. mouse wheel support on relaykeysd
2. mouse lock & report relaykeys-qt
3. accept \t, \n for typing
4. bugfixes & refinements
5. impl #25 show last n chars in qt & mousemove performance imporvement

### CODE REVIEW

**Comment by willwade** [comment]
Im getting a wierd error when I try and verify the arduino sketch:

`Arduino: 1.8.10 (Mac OS X), Board: "Adafruit Bluefruit Feather nRF52840 Express, 0.2.13 SoftDevice s140 6.1.1, Level 0 (Release)"

/Users/willwade/bin/RelayKeys/arduino/arduino_nRF52840/arduino_nRF52840.ino: In function 'void setup()':
arduino_nRF52840:52:49: error: invalid conversion from 'void (*)(uint8_t) {aka void (*)(unsigned char)}' to 'BLEHidAdafruit::kbd_led_cb_t {aka void (*)(short unsigned int, unsigned char)}' [-fpermissive]
   blehid.setKeyboardLedCallback(set_keyboard_led);
                                                 ^
In file included from /Users/willwade/Library/Arduino15/packages/adafruit/hardware/nrf52/0.14.6/libraries/Bluefruit52Lib/src/bluefruit.h:59:0,
                 from /Users/willwade/bin/RelayKeys/arduino/arduino_nRF52840/arduino_nRF52840.ino:14:
/Users/willwade/Library/Arduino15/packages/adafruit/hardware/nrf52/0.14.6/libraries/Bluefruit52Lib/src/services/BLEHidAdafruit.h:58:10: note:   initializing argument 1 of 'void BLEHidAdafruit::setKeyboardLedCallback(BLEHidAdafruit::kbd_led_cb_t)'
     void setKeyboardLedCallback(kbd_led_cb_t fp);
          ^~~~~~~~~~~~~~~~~~~~~~
Multiple libraries were found for "bluefruit.h"
 Used: /Users/willwade/Library/Arduino15/packages/adafruit/hardware/nrf52/0.14.6/libraries/Bluefruit52Lib
Multiple libraries were found for "Adafruit_LittleFS.h"
 Used: /Users/willwade/Library/Arduino15/packages/adafruit/hardware/nrf52/0.14.6/libraries/Adafruit_LittleFS
Multiple libraries were found for "InternalFileSystem.h"
 Used: /Users/willwade/Library/Arduino15/packages/adafruit/hardware/nrf52/0.14.6/libraries/InternalFileSytem
exit status 1
invalid conversion from 'void (*)(uint8_t) {aka void (*)(unsigned char)}' to 'BLEHidAdafruit::kbd_led_cb_t {aka void (*)(short unsigned int, unsigned char)}' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`
Screenshot 2019-11-07 at 12 35 42

**Comment by hosseinamin** [comment]
> Im getting a wierd error when I try and verify the arduino sketch:

This issue is related to API change Adafuit has made. At line 334
```
void set_keyboard_led(uint8_t led_bitmap)
```

And the change requires it to be 
```
void set_keyboard_led(uint16_t conn_handle, uint8_t led_bitmap)
```

Here's an exampl from Adafruit project.
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/Peripheral/hid_keyboard/hid_keyboard.ino#L131

It looks like there is no need to change in the body of that function.

**Comment by willwade** [comment]
Yes that fixes it. Mind pushing to PR? 

Re: Mouse - (I havent properly tested this - need to get test the server code).  Is it capturing in the window - or is it anywhere on screen if the app has focus?

**Comment by hosseinamin** [comment]
> Yes that fixes it. Mind pushing to PR?

Done
 
> Re: Mouse - (I havent properly tested this - need to get test the server code). Is it capturing in the window - or is it anywhere on screen if the app has focus?

When you start the program it will freezes all events a mouse produces, Like it won't not move when the program is running and it's not disabled. No matter where it is.
Drag and drop works. Only I wasn't able to test scrolling with wheel. It can be an issue within PyHook3. I'm using touchpad maybe it requires mouse wheel.

**Comment by hosseinamin** [comment]
A new commit with implementation of #25 has added to this PR.

**Comment by willwade** [comment]
Hmm. Still hanging. Is the problem this mouse capture? Two ideas:
1. A buton in the app to turn on/off mouse capture
2. A capture window (as I cant test it - I dont think this is what we currently have - from what I can tell its capturing the entire screen?? Would a seperate capture-only-in-window help?)

**Comment by hosseinamin** [comment]
I don't any of these will solve this issue.
We already have a disable toggle. By default it is , `Right Alt + A`
But the problem is mouse move sends to many requests and they will get in the queue thus results in this hang issue.
Commit 1312edb was suppose to solve this issue by disabling mouse and keyboard relay after any errors. And typically on timeout or connection error this error will occur after some delay maybe 20-60 seconds.
Are you able to see any logs in relaykeys-qt or relaykeysd?

**Comment by hosseinamin** [comment]
@willwade Please check out my new commit.

**Pull request merged**
