### PR TITLE
BLE mode and small changes

### PR DESCRIPTION
**Pull request by f1andrew**
This pull request contains:
- adding ble mode
- increasing BLE bandwith which improves situation with #80
- other small changes

### CODE REVIEW

**Comment by willwade** [comment]
This looks great. I see you've add ed asyncio more which makes sense. Is requirements.txt up to date?

**Comment by willwade** [comment]
Is serial-wrappers new? Mind giving a brief note what that's doing?

**Comment by willwade** [comment]
Im just dumping this here - once we merge I'll need to update the docs.. easier if we do it once merged really as the docs is now out of sync..

So will need to update docs on the [cli](https://docs.acecentre.org.uk/products/v/relaykeys/developers/reference-2) - and the [serial docs](https://docs.acecentre.org.uk/products/v/relaykeys/developers/reference-1) and I think [daemon](https://docs.acecentre.org.uk/products/v/relaykeys/developers/reference)

For now, mode of work of nrf device is set by ble_mode flag in arduino sketch and requires reupload.
After uploading new version of sketch it's better to unpair and then pair device for first time. Since there added bleuart service.

Relaykeysd starts by default in serial mode, to start it in BLE mode it's needed to add --ble_mode argument.

When working in ble mode first time it's needed to add you central device(laptop) to device list in, regular, serial mode:

1. Send add device command

2. Connect your laptop via bluetooth manually

3. Disconnect your laptop after device added to list. Later it will be connected by python automatically when relaykeysd in ble mode.

**Comment by f1andrew** [comment]
Asyncio used here because bleak library written using asyncio and some functions are required now to be async.
Requirements are up to date, bleak was added and asyncio is built-in library.

serial_wrappers.py is new file.
I put here Dummy serial class from relaykeysd,py and added BLESerialWrapper which allow working with BLE serial using same functions of hardware serial.

**Comment by willwade** [comment]
looking good. This is probably just a qt demo problem - but can you look into BLE switch button - it should be switching between paired devices but it doesnt seem to do anything.. its also something buggy going on in the display of the list

**Comment by willwade** [comment]
image

**Comment by willwade** [comment]
Just getting logic of this straight - to set it up in ble mode

**Comment by f1andrew** [comment]
> Just getting logic of this straight - to set it up in ble mode
> 
>     * Set in Serial USB mode first (Arduino & relaykeysd.py)
> 
>     * Run the relaykeysd.py
> 
>     * Send add device command
> 
>     * Connect your laptop via bluetooth manually
> 
>     * Now change the arduino and relaykeysd to run in BLE mode
> 
> 
> That right?

Yes, but after laptop was manually connected you need to disconnect laptop. 
Next time relaykeysd.py will be connecting it automatically when run.

**Comment by f1andrew** [comment]
> looking good. This is probably just a qt demo problem - but can you look into BLE switch button - it should be switching between paired devices but it doesnt seem to do anything.. its also something buggy going on in the display of the list

I will check BLE switch and correct device list behaviour.

**Comment by willwade** [comment]
We are focusing on https://learn.adafruit.com/introducing-the-adafruit-nrf52840-feather/pinouts - Im wondering if we can make this connecting with a device logic a bit easier. If we use a Button (e.g. User switch)  - which would put it into "Add" loop - this way you could add a device in ble mode - without prior adding it? (But maybe useful in serial mode too). What do you think? Would that work?

**Comment by willwade** [comment]
So nearly there!

Im getting some problems in ble_mode adding a device..

On the device side its seeing it in Bluetooth settings but on the server side Im getting



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\GitHub\RelayKeys\relaykeys-qt.py", line 697, in client_worker
    if not self.client_send_actions(inputlist):
  File "C:\GitHub\RelayKeys\relaykeys-qt.py", line 756, in client_send_actions
    self.showErrorMessageSignal.emit("Failed to send the message!")
RuntimeError: wrapped C/C++ object of type Window has been deleted
PS C:\GitHub\RelayKeys> python .\relaykeys-qt.py
actions ('ble_cmd', 'devname'), ('ble_cmd', 'devlist') raise: Traceback (most recent call last):
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request        
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request        
    httplib_response = conn.getresponse()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request        
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout       
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5383): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GitHub\RelayKeys\relaykeys-qt.py", line 708, in client_send_actions
    ret = self.client.actions(actions)
  File "C:\GitHub\RelayKeys\relaykeysclient.py", line 27, in call
    resp = requests.post(self.url, data, headers=headers, timeout=10.00)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5383): Read timed out. (read timeout=10.0)

actions ('ble_cmd', 'devlist') raise: Traceback (most recent call last):
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request        
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request        
    httplib_response = conn.getresponse()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request        
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout       
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5383): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\GitHub\RelayKeys\relaykeys-qt.py", line 708, in client_send_actions
    ret = self.client.actions(actions)
  File "C:\GitHub\RelayKeys\relaykeysclient.py", line 27, in call
    resp = requests.post(self.url, data, headers=headers, timeout=10.00)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\wwade\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5383): Read timed out. (read timeout=10.0)
`

**Comment by willwade** [comment]
In ble mode - should the server device (the controlling one) be as a keyboard? Should it not be a BLE Serial device?

image

**Comment by f1andrew** [comment]
> In ble mode - should the server device (the controlling one) be as a keyboard? Should it not be a BLE Serial device?
> 
> image

No, after you made connection you need disconnect(press "remove device"). Manual connection is needed only first time to add device into devlist.
After most of issues will be resolved there can be added additional way to add device into devlist.

**Comment by f1andrew** [comment]
Devlist behavior was corrected and switch command now is working.

**Comment by willwade** [comment]
Going to merge this so we can write the Docs on the BLE mode and test the current Installer

**Pull request merged**
