### PR TITLE
added switching to specific device

### PR DESCRIPTION
**Pull request by f1andrew**

### CODE REVIEW

**Comment by willwade** [comment]
@f1andrew what do you think about adding something to help with #153 to this PR? Workable?

**Comment by joedevsys** [comment]
After a few seconds I get the "trying to switch to " notification. then after a few more seconds a command window pops up for a short time: AppInstallerPythonRedirector.exe but no further notification.   (Connection succeeds quietly).

**Comment by f1andrew** [comment]
Here is isolated test of sending notification from background process.
Main.py should launch background subprocess and return then subprocess_file.py after delay should send notification.
Try to run it on communicator and let me know does it work.

[subprocess_test.zip](https://github.com/AceCentre/RelayKeys/files/12671838/subprocess_test.zip)

**Comment by joedevsys** [comment]
Calling "python Mainpy" from Communicator5 (fullscreen): during the delay while subprocess_file.py is running a python cmd window appears on top of Communicator (not good!). Later this gets closed and a notification pops up (good!).

Renamed both files to .pyw. Changed main.pyw to call "subprocess_file.exe" and compiled both using Pyinstaller. This now works correctly. No command window is displayed and a notification appears after a few seconds. 

(I did not succeed with the Pyinstaller --onefile switch. This causes main.exe to not find subprocess_file.exe. I probably need to fix paths somewhere. --onefile is ok with subprocess_file.exe but not with main.exe)

**Comment by willwade** [comment]
I've added this as a draft release to aid anyone's testing https://github.com/AceCentre/RelayKeys/releases/tag/2.01 (@quaxalber   - I've recreated all the UF2 files )

**Comment by f1andrew** [comment]
Previously I tested it only with Python.
I've added poll_devname into build and added option of running built exe.
So now built version should be working too.

**Comment by willwade** [comment]
Fab! I've updated the Pre-release with the full updated installer . Thanks @f1andrew

**Comment by quaxalber** [comment]
> I've updated the Pre-release with the full updated installer

The updated installer yields this error for me @willwade 

image

Apologies for the delay on my end. I've been working on [my other project](https://github.com/quaxalber/bluetooth_2_usb), which is a nice addition for my setup. I'm thinking if you might want to integrate it into RK? Since this is probably not the right place for discussion, feel free to email me your thoughts.

**Comment by willwade** [comment]
Ah. I don't know why thar error is happening. I'll look into that. Re Bluetooth -> hid did you see our dongle code. It basically does this but designed for relaykeys. The other way we have done this is on a esp32. But like it! I know a team desperate for that setup https://github.com/AceCentre/open-ble-screen

**Comment by quaxalber** [comment]
> did you see our [dongle recieving code](https://github.com/AceCentre/RelayKeys/tree/master/arduino/receiver_dongle)?

I was aware of this feature, but for some reason I ditched this idea early on, because in my head I thought it wouldn't work on my work notebook, since its endpoint security blocks any Bluetooth interfaces (including Bluetooth dongles). But the RK receiver would identify itself as HID, just like my solution, right? Do you think it would work to plug the RK receiver into a KVM switch? 

> I know a team desperate for that setup

Sounds great, glad if this helped others too. 

> But I like your pi approach!

Thanks @willwade ! :)

**Comment by f1andrew** [comment]
@willwade 
This is because of pyinstaller update. They released new version 6.0 on sep 23.
It's building somehow different and causes issue with path. 
I will look more about it.

For now, it's better to revert to 5.13.2 and build it again. Build made with this version works.
Here is command for reverting pyinstaller version:
`pip install --force-reinstall pyinstaller==5.13.2`

**Comment by willwade** [comment]
Thanks @f1andrew  - I'm going to merge this - I cant see it breaking anything and it will be easier to test. I have a feeling the pyinstaller on the GH Action pipeline wont be updated so I'll see if the same thing is happening there.

**Pull request merged**
