### PR TITLE
testing changing name to fix for i13 issue #125

### PR DESCRIPTION
**Pull request by willwade**
re: #125 

Needs testing this

### CODE REVIEW

**Comment by willwade** [comment]
to save myself from hunting around for it - compiled build of this: [Windows Release](https://github.com/AceCentre/RelayKeys/suites/8286248393/artifacts/363133542)

**Comment by joedevsys** [comment]
That worked (once I remembered to apply the dongle name change as well).

Very strange, wonder why it didn't work with "RelayKeys"?

**Comment by willwade** [comment]
It’s super wierd. If it had the name relay in it at all it refused to see it. Very odd.

**Comment by joedevsys** [comment]
Weird, but good to have found a fix.  Should use RealyKeys instead as I'm always mistyping that ;-).

I'm not sure if this is possible, but might be useful if every dongle identifies with a different name so they can be distinguished if there are several active nearby e.g. AceRKxxx where xx is generated from the mac address.  Whether to bother depends how hard that is to implement at the daemon end. 

The procedure for initiating wireless mode needs more detailed description and may not always work reliably first time round.

**Pull request merged**
